### ISSUE TITLE
Json.nostrict deprecated

### ISSUE THREAD

**Issue by Queatz** [polygon-io/client-jvm#25]
I am getting the following error when compiling:

Edit: This error appeared when I added `org.drewcarlson:coingecko` as a dependency, excluding `io.ktor` on that package made the below error go away.

```
Exception in thread "DefaultDispatcher-worker-1" java.lang.NoSuchFieldError: Companion
	at io.polygon.kotlin.sdk.DefaultJvmHttpClientProvider$buildClient$1$1.invoke(HttpClientProvider.kt:64)
	at io.polygon.kotlin.sdk.DefaultJvmHttpClientProvider$buildClient$1$1.invoke(HttpClientProvider.kt:52)
	at io.ktor.client.HttpClientConfig$install$2.invoke(HttpClientConfig.kt:69)
	at io.ktor.client.HttpClientConfig$install$2.invoke(HttpClientConfig.kt:65)
	at io.ktor.client.features.json.JsonFeature$Feature.prepare(JsonFeature.kt:129)
	at io.ktor.client.features.json.JsonFeature$Feature.prepare(JsonFeature.kt:125)
	at io.ktor.client.HttpClientConfig$install$3.invoke(HttpClientConfig.kt:77)
	at io.ktor.client.HttpClientConfig$install$3.invoke(HttpClientConfig.kt:74)
	at io.ktor.client.HttpClientConfig.install(HttpClientConfig.kt:97)
	at io.ktor.client.HttpClient.<init>(HttpClient.kt:172)
	at io.ktor.client.HttpClient.<init>(HttpClient.kt:81)
	at io.ktor.client.HttpClientKt.HttpClient(HttpClient.kt:62)
	at io.polygon.kotlin.sdk.DefaultJvmHttpClientProvider.buildClient(HttpClientProvider.kt:61)
	at io.polygon.kotlin.sdk.rest.AggregatesKt.getAggregates(Aggregates.kt:85)
```

Kotlin: 1.5.31
Ktor: 1.6.5

**Comment by Queatz** [comment]
```kotlin
serializer = KotlinxSerializer(Json {
    isLenient = true
    ignoreUnknownKeys = true
})
```

possible replacement

**Comment by ssoper** [comment]
I got this issue as well and the solution was to set the version of ktor to 1.3.1, the same version that comes with the `client-jvm` library.  If the maintainers could release a new version of the package with updated dependencies (ktor >= 1.6.5) that would be greatly appreciated.

**Comment by ssoper** [comment]
well drat, this caused some add’l errors on attempting to build

```
> Task :kaptGenerateStubsKotlin FAILED
e: kotlin.KotlinNullPointerException
	at org.jetbrains.kotlinx.serialization.compiler.resolve.SearchUtilsKt.getKSerializerConstructorMarker(SearchUtils.kt:64)
	at org.jetbrains.kotlinx.serialization.compiler.resolve.KSerializerDescriptorResolver.createLoadConstructorDescriptor(KSerializerDescriptorResolver.kt:293)
	at org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationResolveExtension.generateSyntheticSecondaryConstructors(SerializationResolveExtension.kt:85)
	at org.jetbrains.kotlin.resolve.extensions.SyntheticResolveExtension$Companion$getInstance$1.generateSyntheticSecondaryConstructors(SyntheticResolveExtension.kt:121)
	at org.jetbrains.kotlin.resolve.lazy.descriptors.LazyClassMemberScope.addSyntheticSecondaryConstructors(LazyClassMemberScope.kt:442)
	at org.jetbrains.kotlin.resolve.lazy.descriptors.LazyClassMemberScope.doGetConstructors(LazyClassMemberScope.kt:437)
	at org.jetbrains.kotlin.resolve.lazy.descriptors.LazyClassMemberScope.access$doGetConstructors(LazyClassMemberScope.kt:49)
	at org.jetbrains.kotlin.resolve.lazy.descriptors.LazyClassMemberScope$secondaryConstructors$1.invoke(LazyClassMemberScope.kt:432)
…
```

**Comment by ssoper** [comment]
Ok created a [PR](https://github.com/polygon-io/client-jvm/pull/27) with passing build, lmk if you have questions, concerns, etc, thanks.

**Comment by ssoper** [comment]
FYI it appears the build on that PR is stuck…

**Comment by Queatz** [comment]
Still needing this...

**Comment by Grigoriy1987** [comment]
Still needing this...

**Comment by mmoghaddam385** [comment]
This should be resolved with the various updates to dependencies in the latest release, please re-open this issue if this is still a problem
