### ISSUE TITLE
with your kotlin sample, and with the POLYGON_API_KEY defined with a 7 day trial account - 403 forbidden

### ISSUE THREAD

**Issue by sk92129** [polygon-io/client-jvm#4]
I cloned your kotlin/java sample.
https://github.com/polygon-io/client-jvm
I defined the POLYGON_API_KEY in my .bash_profile similar to this:

export POLYGON_API_KEY="pRV<snipped>O7y"

Then I ran : ./gradlew kotlinSample

Then I got this error:

(base) Seans-MacBook-Pro-2:client-jvm sean$ ./gradlew kotlinSample

> Task :sample:kotlinSample
Blocking for markets...
Exception in thread "main" io.ktor.client.features.ClientRequestException: Client request(https://api.polygon.io/v2/reference/markets?apiKey=pRV1C<snipped>DsO7y) invalid: 403 Forbidden
        at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invokeSuspend(DefaultResponseValidation.kt:35)
        at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(DefaultResponseValidation.kt)
        at io.ktor.client.features.HttpCallValidator.validateResponse(HttpCallValidator.kt:35)
        at io.ktor.client.features.HttpCallValidator$Companion$install$2.invokeSuspend(HttpCallValidator.kt:96)
        at io.ktor.client.features.HttpCallValidator$Companion$install$2.invoke(HttpCallValidator.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:273)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:141)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:161)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)
      etc.

**Comment by sk92129** [comment]
Nevermind -- I realized that I did not go thru the entire subscription sign up and go thru those multiple pages of agreements and put a credit card.
